export const notesv2 = [
  ['C', 'DO'],
  ['D', 'RE'],
  ['E', 'MI'],
  ['F', 'FA'],
  ['G', 'SOL'],
  ['A', 'LA'],
  ['B', 'SI'],
]

export const chordsv2 = {
  '5': [
    ['LA', 'A'],
    ['LAm', 'Am'],
    ['LAb', 'Ab'],
    ['LAbm', 'Abm'],
    ['LAsharp', 'Asharp'],
    ['LAsharpm', 'Asharpm'],
    ['LAdim', 'Adim'],
    ['LAsharpdim', 'Asharpdim'],
    ['LA7', 'A7'],
    ['LAaug', 'Aaug'],
    ['LAmaj7', 'Amaj7'],
    ['LAsharpaug', 'Asharpaug'],
  ],
  '6': [
    ['SI', 'B'],
    ['SIm', 'Bm'],
    ['SIb', 'Bb'],
    ['SIbm', 'Bbm'],
    ['SIdim', 'Bdim'],
    ['SI7', 'B7'],
    ['SIaug', 'Baug'],
    ['SImaj7', 'Bmaj7'],
  ],
  '0': [
    ['DO', 'C'],
    ['DOm', 'Cm'],
    ['DOsharp', 'Csharp'],
    ['DOsharpm', 'Csharpm'],
    ['DOdim', 'Cdim'],
    ['DOsharpdim', 'Csharpdim'],
    ['DO7', 'C7'],
    ['DOaug', 'Caug'],
    ['DOmaj7', 'Cmaj7'],
    ['DOsharpaug', 'Csharpaug'],
  ],
  '1': [
    ['RE', 'D'],
    ['REm', 'Dm'],
    ['REb', 'Db'],
    ['REbm', 'Dbm'],
    ['REsharp', 'Dsharp'],
    ['REsharpm', 'Dsharpm'],
    ['REdim', 'Ddim'],
    ['REsharpdim', 'Dsharpdim'],
    ['RE7', 'D7'],
    ['REaug', 'Daug'],
    ['REmaj7', 'Dmaj7'],
    ['REsharpaug', 'Dsharpaug'],
  ],
  '2': [
    ['MI', 'E'],
    ['MIm', 'Em'],
    ['MIb', 'Eb'],
    ['MIbm', 'Ebm'],
    ['MIdim', 'Edim'],
    ['MI7', 'E7'],
    ['MIaug', 'Eaug'],
    ['MImaj7', 'Emaj7'],
  ],
  '3': [
    ['FA', 'F'],
    ['FAm', 'Fm'],
    ['FAsharp', 'Fsharp'],
    ['FAsharpm', 'Fsharpm'],
    ['FAdim', 'Fdim'],
    ['FAsharpdim', 'Fsharpdim'],
    ['FA7', 'F7'],
    ['FAaug', 'Faug'],
    ['FAmaj7', 'Fmaj7'],
    ['FAsharpaug', 'Fsharpaug'],
  ],
  '4': [
    ['SOL', 'G'],
    ['SOLm', 'Gm'],
    ['SOLb', 'Gb'],
    ['SOLbm', 'Gbm'],
    ['SOLsharp', 'Gsharp'],
    ['SOLsharpm', 'Gsharpm'],
    ['SOLdim', 'Gdim'],
    ['SOLsharpdim', 'Gsharpdim'],
    ['SOL7', 'G7'],
    ['SOLaug', 'Gaug'],
    ['SOLmaj7', 'Gmaj7'],
    ['SOLsharpaug', 'Gsharpaug'],
  ],
}
